---
- name: Ensure apt requirements
  ansible.builtin.package:
    name: apt-transport-https
    state: present

- name: Add the Sublime pgp key
  ansible.builtin.apt_key:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    state: present

- name: Add Sublime Repository
  ansible.builtin.apt_repository:
    repo: "deb https://download.sublimetext.com/ apt/stable/"
    state: present
    filename: sublime

- name: Install Sublime-Text
  ansible.builtin.apt:
    name: sublime-text
    update_cache: true
    state: present

- name: Set Sublime as default editor
  ansible.builtin.lineinfile:
    path: /usr/share/applications/mimeapps.list
    insertafter: "[Default Applications]"
    line: "{{ item.key }}={{ item.value }}"
  loop: "{{ sublime_mimetypes | dict2items }}"
