---
- name: Ensure apt requirements
  ansible.builtin.package:
    name: apt-transport-https
    state: present

- name: Add the Sublime pgp key
  ansible.builtin.apt_key:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    state: present

- name: Add Sublime Repository
  ansible.builtin.apt_repository:
    repo: "deb https://download.sublimetext.com/ apt/stable/"
    state: present
    filename: sublime

- name: Install Sublime-Text
  ansible.builtin.apt:
    name: sublime-text
    update_cache: true
    state: present

- name: Configure defaults file
  ansible.builtin.lineinfile:
    path: /usr/share/applications/mimeapps.list
    line: "{{ item }}"
    state: present
    create: true
    mode: "0644"
    owner: root
    group: root
  loop:
    - "[Default Applications]"
    - "[Added Associations]"

- name: Set Sublime default application
  ansible.builtin.lineinfile:
    path: /usr/share/applications/mimeapps.list
    insertbefore: "Added Associations"
    line: "{{ item }}=sublime_text.desktop"
    state: present
    firstmatch: true
  loop: "{{ sublime_mimetypes | sort }}"

- name: Set Sublime added associations
  ansible.builtin.lineinfile:
    path: /usr/share/applications/mimeapps.list
    insertafter: "Added Associations"
    line: "{{ item }}=sublime_text.desktop"
    state: present
    firstmatch: true
  loop: "{{ sublime_mimetypes | sort }}"
