---
- name: Add Sublime repo using key from URL
  ansible.builtin.deb822_repository:
    name: sublimetext
    types: [deb]
    uris: "https://download.sublimetext.com/"
    suites: ["apt/stable/"]
    signed_by: https://download.sublimetext.com/sublimehq-pub.gpg
    state: present
    enabled: true

- name: Install Sublime-Text
  ansible.builtin.apt:
    name: sublime-text
    update_cache: true
    state: present

- name: Configure sublime as default application
  include_tasks: set_default_app.yml
  loop: "{{ sublime_os_users }}"
  loop_var: os_user
