---
- name: Set Sublime default application
  community.general.gio_mime:
    mime_type: "{{ mimetype }}"
    handler: sublime_text.desktop
  loop: "{{ sublime_mimetypes }}"
  loop_control:
    loop_var: mimetype
  become: true
  become_user: "{{ item }}"
