---
- name: Set Sublime default application
  community.general.gio_mime:
    mime_type: "{{ item }}"
    handler: sublime_text.desktop
  loop: "{{ sublime_mimetypes }}"
  become: true
  become_user: "{{ os_user }}"
